### ISSUE TITLE
Bot doesn't add commands to the server

### ISSUE THREAD

**Issue by Dhruvgera** [mishalhossin/Gpt3-sexbot-discord#3]
Adding bot doesn't seem to add commands to the server like the gpt discord bot, nor do the commands like !welp or !ping work with freebot script

**Comment by mishalhossin** [comment]
okay cope

**Comment by Dhruvgera** [comment]
> okay cope

lmao based

**Comment by revolutionarycomrade** [comment]
I'm garbage at python but adding:
`if message.content == '!toggleactive':
ctx = await bot.get_context(message)
await toggleactive(ctx)`
 in the on_message() event enabled me to interact with the bot by adding or removing channels through typing !toggleactive

**Comment by mishalhossin** [comment]
we are using /slash commands now so you have to give perms when you invite

**Comment by revolutionarycomrade** [comment]
I just gave the bot all permissions and it worked so why not I guess

**Comment by revolutionarycomrade** [comment]
The bot also doesn't seem to offer an option for sending slash commands

**Comment by revolutionarycomrade** [comment]
I only found this repo yesterday, and cloned it yesterday. I'm using the freebot.py file, if that helps at all. Anyways, many thanks for your bot, it has worked quite well.

**Comment by mishalhossin** [comment]
> I only found this repo yesterday, and cloned it yesterday. I'm using the freebot.py file, if that helps at all. Anyways, many thanks for your bot, it has worked quite well.

oh fuck i forgot this was the other repo

**Comment by mishalhossin** [comment]
i was talking about https://github.com/mishalhossin/Discord-Chatbot-Gpt4Free my bad

**Comment by revolutionarycomrade** [comment]
Oh, no worries. I really appreciate your work in this

**Comment by Dhruvgera** [comment]
> I'm garbage at python but adding:
> 
> `if message.content == '!toggleactive': ctx = await bot.get_context(message) await toggleactive(ctx)`
> 
> in the on_message() event enabled me to interact with the bot by adding or removing channels through typing !toggleactive

Thanks a bunch! Seems to have worked just fine!
